sudo: required

language: java

services:
  - mysql
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

script:
  - bash build_and_run_rest_api_test.sh

notifications:
  email:
    recipients:
      - gabilampard@gmail.com

    on_success: always
    on_failure: always