server:
  port: 8080
  context-path: /sample


spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  output:
    ansi:
      enabled: DETECT


logging:
  file: logs/sample-microservice.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.hyrax.microservice.sample: DEBUG